/*
 * SSD_cfg.h
 *
 *  Created on: Aug 22, 2023
 *      Author: Mohanad
 */

#ifndef HAL_SSD_SSD_CFG_H_
#define HAL_SSD_SSD_CFG_H_

/*	SSD1	*/
/*GPIO_PORTA ...GPIO_PORTB... GPIO_PORTC*/
#define SSD1_PORTA   GPIO_PORTA
#define SSD1_PORTB   GPIO_PORTA
#define SSD1_PORTC   GPIO_PORTA
#define SSD1_PORTD   GPIO_PORTA
#define SSD1_PORTE   GPIO_PORTA
#define SSD1_PORTF   GPIO_PORTA
#define SSD1_PORTG   GPIO_PORTA
/*GPIO_PIN0 ...... GPIO_PIN15*/
#define SSD1_PINA   GPIO_PIN0
#define SSD1_PINB   GPIO_PIN1
#define SSD1_PINC   GPIO_PIN2
#define SSD1_PIND   GPIO_PIN3
#define SSD1_PINE   GPIO_PIN4
#define SSD1_PINF   GPIO_PIN5
#define SSD1_PING   GPIO_PIN6

/*	SSD2	*/
/*GPIO_PORTA ...GPIO_PORTB... GPIO_PORTC*/
#define SSD2_PORTA   GPIO_PORTA
#define SSD2_PORTB   GPIO_PORTA
#define SSD2_PORTC   GPIO_PORTA
#define SSD2_PORTD   GPIO_PORTA
#define SSD2_PORTE   GPIO_PORTA
#define SSD2_PORTF   GPIO_PORTA
#define SSD2_PORTG   GPIO_PORTA
/*GPIO_PIN0 ...... GPIO_PIN15*/
#define SSD2_PINA   GPIO_PIN7
#define SSD2_PINB   GPIO_PIN8
#define SSD2_PINC   GPIO_PIN9
#define SSD2_PIND   GPIO_PIN10
#define SSD2_PINE   GPIO_PIN11
#define SSD2_PINF   GPIO_PIN12
#define SSD2_PING   GPIO_PIN13

#endif /* HAL_SSD_SSD_CFG_H_ */
